### ISSUE TITLE
[Query for Address.cs] How do you SHA256 a hex value?

### ISSUE THREAD

**Issue by AngeloMetal** [Autarkysoft/Denovo#5]
A Bitcoin address requires the hash of the public key as a hex value and not as a text.

I've been searching for a way to perform SHA256 to a hex value and not to a text, but Google doesn't seem to help me. On your Encoders/Address.cs you do that, but I haven't understood how. Specifically, you do it on <a href="https://github.com/Autarkysoft/Denovo/blob/7014f234758011d1ee1e8f337b2011a8f20e16cb/Src/Autarkysoft.Bitcoin/Encoders/Address.cs#L166-L167">L166-L167</a>. What part of it does it convert the string to hex? Is it the fact that you hash it as bytes instead of string?

**Comment by Coding-Enthusiast** [comment]
There is no string to convert, there is a `PublicKey` that is converted to its byte array representation which is then hashed using the `Sha256` instance.  

PS. Please post your questions in the discussions section under Q&A.
